### ISSUE TITLE
list(note)[0]["id"] IndexError: list index out of range

### ISSUE THREAD

**Issue by ValentinWalter** [rberenguel/bear-note-graph#3] opened 2020-04-20 08:41 UTC
Getting this in 0.1.3
```
INFO - Copying Bear database to /tmp/BearExportTemp.sqlite
INFO - Fetching notes from (the copy of the) database
INFO - Fetched 340 notes from the (copy of) the Bear database
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/bear-note-graph", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/main.py", line 122, in main
    generate_graph(graph_format)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bear_note_graph/generate.py", line 106, in generate_graph
    note_edge["dst"] = list(note)[0]["id"]
IndexError: list index out of range
```

**Comment by rberenguel** [comment] 2020-04-20 10:27
Thanks @ValentinWalter This one looks weird, I'll investigate later!

**Comment by rberenguel** [comment] 2020-04-20 17:42
@ValentinWalter this should be fixed in version 0.1.4 (or at least the error message should tell what the issue is exactly now)

**Comment by ValentinWalter** [comment] 2020-04-21 14:25
Yep, it's a different error now.

**Closed as completed** 2020-04-21 14:25 UTC

**Comment by rberenguel** [comment] 2020-04-21 14:30
@ValentinWalter that is only marginally better, but moving forward :D
